services:
  mysql:
    image: mysql:9.7
    container_name: coffee-mysql
    environment:
      MYSQL_DATABASE: coffee
      MYSQL_USER: coffee
      MYSQL_PASSWORD: coffee
      MYSQL_ROOT_PASSWORD: coffee
    ports:
      - "13306:3306"
    command: --default-time-zone=+09:00
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -ucoffee -pcoffee -e 'USE coffee_test' || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 20